- package-lock.json
- src/App.js
- src/layouts/HomeLayout.js
- src/layouts/PublicLayout.js
- src/page/Dashboard/index.js
- src/route/route.js
Currently If user tries to access "/index.html" route they are able to view dashboard without login.
This PR fixes this issue so that If user trying to access "/index.html" route they automatically redirect to login page without login HomeLayout is not accessible.
src/layouts
- /HomeLayout.js :  This layout for the logged in user. User can access or view only private things (Like Navbar and Dashboard etc.)
- /PublicLayout.js :  This layout is for the public (Like login, signup, forget or the thing that is not required login)
src/route
- routes.js : This file have all the public and home layout with lazy loading, It means handling layouts and render component If required.
> Enhance login security

- src/components/Layout/Navbar.js
- src/components/Layout/Sidebar.js
- src/components/PillFilter/index.js
- src/page/Login/index.js
This PR resolved #36 
Replaced the required divs into button
src/components/Layout/Sidebar.js
src/components/PillFilter/index.js
src/page/Login/index.js
> Div button replace

- package.json
- src/components/Button/index.js
- src/components/Checkbox/index.js
- src/components/Dropdown/index.js
- src/components/DropdownButton/index.js
- src/components/Layout/Dialogue.js
- src/components/Layout/Navbar.js
- src/components/Layout/Sidebar.js
- src/components/Layout/index.js
- src/components/MultiSelectDropdown/index.js
- src/components/Pill/index.js
- src/components/PillFilter/index.js
- src/components/PillFilterList/index.js
- src/components/SearchableDropdown/index.js
- src/components/SideDialog/index.js
> Add PropTypes to shared components

- src/hooks/useQueryLogs.ts
- src/pages/Logs/Column.tsx
- src/pages/Logs/LogRow.tsx
- src/pages/Logs/LogTable.tsx
- src/utils/index.ts
This PR includes
- Ability to filter columns
> Feat: Column filtering

- src/components/Navbar/styles.tsx
- src/constants/theme.ts
- src/pages/Logs/Column.tsx
- src/pages/Logs/styles.tsx
> UI changes

- src/@types/parseable/api/query.ts
- src/hooks/useQueryLogs.ts
- src/layouts/MainLayout/Context.tsx
- src/pages/Logs/Column.tsx
- src/pages/Logs/LogTable.tsx
Changes:
- Added option to sort by a given field (addresses #90)
Tested implemented functionality by opening a field filter popover and selecting one of the sorting icons
Sorts by descending order of p_timestamp by default. Selecting the currently selected sort icon resets to default option above.
> feat: add option to sort by a column

- src/components/Navbar/index.tsx
- src/pages/Query/QueryCodeEditor.tsx
- src/pages/Stats/Status.tsx
there are three bugs caused or new page change handler 
1 . `Navbar/index.tsx` if users change the page (not stream) it was not reseting the context .
2 . `console/queryeditor.tsx` if users change the time range it reset the query to default .
3.  `stats/index.tsx` if a stream doesn't receive event form last seven day that returns `no events received in past 2 months`
> [Bugs] page change context reset, query page time range context change ,stats status duration limit

- src/api/query.ts
- src/pages/Logs/CarouselSlide.tsx
- src/pages/Logs/HeaderPagination.tsx
- src/pages/Logs/styles.tsx
https://console-q43dmm32l-kartik-gupta-ij.vercel.app/backend/logs
> Pagination modification

- src/components/Navbar/index.tsx
- src/routes/index.tsx
Temporary patch for #176 
Similar issue: https://stackoverflow.com/questions/67078147/struggling-to-make-grpc-web-and-https-work
> ISSUE-176 - conditionally hide live tail for https protocol

- src/components/Header/TimeRange.tsx
- src/hooks/useOuterClick.ts
Since there is no support to pass ref to Mantine's datepicker modal, implemented useOuterClick that ensures that the time range popover doesn't close unintentionally when the user interacts with the calendar.
> implemented useOuterClick - mantine calendar modal issue

- src/api/logStream.ts
- src/components/Navbar/UserModal.tsx
- src/hooks/useAlertsEditor.tsx
- src/hooks/useCacheToggle.tsx
- src/hooks/useRetentionEditor.tsx
- src/hooks/useRole.tsx
- src/hooks/useUser.tsx
- src/pages/AccessManagement/PrivilegeTR.tsx
- src/pages/AccessManagement/RoleTR.tsx
- src/pages/AccessManagement/Users.tsx
- src/pages/Home/index.tsx
- src/pages/Logs/AlertsModal.tsx
- src/pages/Logs/LogTable.tsx
- src/pages/Logs/RetentionModal.tsx
- src/pages/Logs/index.tsx
- src/utils/notification.ts
> further fixes 

- src/components/Navbar/index.tsx
- src/components/Navbar/rolesHandler.ts
- src/constants/routes.ts
- src/layouts/MainLayout/Context.tsx
- src/pages/Logs/EventTimeLineGraph.tsx
- src/pages/Logs/LogTable.tsx
- src/pages/Systems/Ingestors.tsx
- src/pages/Systems/styles/Systems.module.css
- src/routes/index.tsx
1. The Cluster page URL has been updated.
2. Added admin specific access to admin for cluster page
3. Time range updates on the event timeline graph - use complete minute intervals
4. rm alias from total event count query
5. Ingestor table modifications
> Distributed systems feedbacks

- src/pages/Logs/EventTimeLineGraph.tsx
fix: reduced the end time difference from 2 to 0
so that graph is displayed till last minute
> fix for graph not showing events for last 2 mins

- README.md
- src/components/Header/TimeRange.tsx
- src/pages/Stream/components/EventTimeLineGraph.tsx
- src/pages/Stream/providers/LogsProvider.tsx
1. Added tooltip to shift interval btns and time range btn.
2. Timerange button label and chart tooltip will now use 12hr format. 
3.
> Timerange btn UI fixes

- src/pages/Stream/Views/Explore/StaticLogRow.tsx
- src/pages/Stream/styles/Logs.module.css
The button is positioned absolute to the table division.
> Changes: Styling changes on copy button on log table

- src/pages/Home/index.tsx
- src/pages/Stream/styles/Logs.module.css
This PR fixes the issue where the header was scrollable on having multiple streams on the home page The section showing the All Streams title and the create stream button should be sticky
>  Fix: Sticky header on homepage

- src/pages/Stream/components/Querier/FilterQueryBuilder.tsx
- src/pages/Stream/components/Querier/QueryCodeEditor.tsx
- src/pages/Stream/components/Querier/index.tsx
- src/pages/Stream/styles/Querier.module.css
- src/pages/Stream/styles/QueryCode.module.css
This PR adds two buttons to the querier modal which allows the user to switch query within the modal from filter query to sql query and vice versa
> Feature: Switch Querier Modal

- src/pages/Stream/Views/Explore/StaticLogRow.tsx
- src/pages/Stream/components/Querier/QueryCodeEditor.tsx
- src/pages/Stream/components/Querier/SavedFiltersModal.tsx
- src/pages/Stream/components/Querier/index.tsx
- src/pages/Stream/providers/LogsProvider.tsx
Fixes for: 
1. Reset saved filter context on stream change
2. Respect new line character in log table cell
> clear filter context on stream change

- src/hooks/useQueryLogs.ts
- src/hooks/useQueryResult.tsx
- src/pages/Stream/Views/Explore/Footer.tsx
- src/pages/Stream/Views/Explore/JSONView.tsx
- src/pages/Stream/Views/Explore/LogsView.tsx
- src/pages/Stream/Views/Explore/StaticLogTable.tsx
- src/pages/Stream/Views/Explore/useLogsFetcher.ts
This pr fix the bug where queries are not fired on change of time range for footer count.
> Fix: Footer Count Error

- src/pages/Dashboards/CreateTileForm.tsx
Bug:
It was showing 'Create Tile' as the header on the edit form.
> Fix: show correct header on tiles form

- src/pages/Stream/Views/Explore/Footer.tsx
- src/pages/Stream/providers/LogsProvider.tsx
On changing offset the page was not set to the first available. This PR makes sure the previous selected page is not set for the newly fetched logs
> Fix: On changing page offset it will always pick the first available page

- src/pages/Stream/components/Querier/index.tsx
- src/pages/Stream/providers/FilterProvider.tsx
Previously on adding a saved filter and then removing the a condition the filter builder will close the modal and apply the remaining condition. This PR changes the flow and waits for the user to click the apply button.
> Fix: Filter builder was applying filter on removing rules

- src/pages/Stream/providers/LogsProvider.tsx
The current build of console stores the filters even when the stream is changed. This PR fixes the issue by reseting the applied filters
> fix : Reset table filters on stream change

- .gitignore
- src/pages/AccessManagement/Roles.tsx
- src/pages/AccessManagement/Users.tsx
The current create user modal allows to create user without any role specified.
The create role action also allows to create a role without a privilege.
**Changes**
This  PR makes sure that the create button is disabled unless the role is selected by the user
For create role this pr makes sure both role name and privilege is set before allowing the user to create a role
>  Fix: Create User action

- src/@types/parseable/api/about.ts
- src/@types/parseable/api/query.ts
- src/api/constants.ts
- src/api/query.ts
- src/hooks/useGetStreamInfo.tsx
- src/hooks/useQueryLogs.ts
- src/hooks/useQueryResult.tsx
- src/pages/Stream/Views/Explore/LogsView.tsx
- src/pages/Stream/Views/Explore/useLogsFetcher.ts
- src/pages/Stream/Views/Manage/Management.tsx
- src/pages/Stream/Views/Manage/UpdateCustomPartitionField.tsx
- src/pages/Stream/Views/Manage/UpdateTimePartitionLimit.tsx
- src/pages/Stream/components/EventTimeLineGraph.tsx
- src/pages/Stream/components/Querier/QueryCodeEditor.tsx
- src/pages/Stream/components/Querier/SavedFiltersModal.tsx
- src/pages/Stream/components/Querier/index.tsx
- src/pages/Stream/index.tsx
- src/pages/Stream/providers/FilterProvider.tsx
- src/utils/queryBuilder.ts
Support for multiple query engine
**Changes**
- new class implementation which generates new query and resource path based on the query engine
- new filter query class which generates new filter query
- SQL query based on based on query engine
> Query engine

- src/hooks/useQueryResult.tsx
This PR changes the footer query and removes the offset and limit part
> Changes to footer query

- src/layouts/MainLayout/index.tsx
- src/layouts/MainLayout/providers/AppProvider.tsx
- src/pages/AccessManagement/Users.tsx
- src/pages/Home/index.tsx
- src/pages/Stream/Views/Explore/JSONView.tsx
- src/pages/Stream/Views/Explore/StaticLogRow.tsx
- src/pages/Stream/Views/Explore/StaticLogTable.tsx
- src/pages/Stream/components/ViewLog.tsx
- src/pages/Systems/MachineInfo.tsx
**Description**
The copy button is visible when a cell is empty in the logs view.
For in-secure context(HTTP) copy button is visible even though the clipboard is not accessible.
**FIXES**
- Copy button wont be visible when the cell value is empty in the logs table
- copy button and copy action will not be available for in-secure sessions
> Changes to copy button

- src/@types/parseable/api/savedFilters.ts
- src/hooks/useSavedFilters.tsx
- src/pages/Stream/components/Querier/FilterQueryBuilder.tsx
- src/pages/Stream/components/Querier/SaveFilterModal.tsx
- src/pages/Stream/components/Querier/SavedFiltersModal.tsx
- src/pages/Stream/hooks/useParamsController.ts
- src/pages/Stream/providers/LogsProvider.tsx
- src/pages/Stream/utils.ts
Added `filter_query` to all types of filters.
Testing Scenarios:
1. When the query is present in the query parameter, and the page is refreshed:
Current Behavior: The query is applied but it shows filter type as SQL
Expected Behavior: The query should be applied with appropriate filter type view in the filter section.
2. When a filter is saved:
Current Behavior: filter_builder is being sent in the payload.
Expected Behavior: `filter_builder` will not be sent, instead `filter_query` will have the query.
3. When a filter is saved:
Current Behavior: `filter_builder` is being sent in the payload.
Expected Behavior: `filter_builder` will not be sent, instead `filter_query` will have the query.
4. When a saved filter is applied:
Current Behavior: The filter query  is applied but it always shows …
> Added filter_query to filter builder

- tests/login.spec.ts
Test cases:
- Added tests to verify page title on login page
- Implemented login test with valid credentials, verifying successful navigation to dashboard
- Added test for invalid login to check for error message display
- Included test to ensure login button is disabled with incomplete form
- Added test to confirm error message appears for failed login
- Implemented OAuth login button test to verify redirection to OAuth login URL
These tests enhance coverage for login functionality, handling both successful and error cases.
> Login flow Playwright test cases

- src/pages/AccessManagement/styles/AccessManagement.module.css
- Fixed height mismatch between buttons in users and roles section.
Before:
After:
> Fixed the height mismatch for create user button

- src/pages/Dashboards/Dashboard.tsx
- src/pages/Dashboards/Toolbar.tsx
- src/pages/Dashboards/styles/DashboardView.module.css
- src/pages/Dashboards/styles/toolbar.module.css
Fixes #366 
- Moved the delete dashboard modal confirmation text from placeholder to modal content.
- Corrected the class spelling for 'tilesViewContainer'.
- Added some margin at the bottom of the tiles container in dashboard.
BEFORE:
AFTER:
> UX improvement delete dashboard modal

- src/pages/Stream/components/EventTimeLineGraph.tsx
- OFFSET query should not be sent in `EventTimeLineGraph` fetch query.
> Removing OFFSET during SQL sanitisation

- src/hooks/useGetStreamInfo.tsx
- src/pages/Stream/Views/Explore/useLogsFetcher.ts
- src/pages/Stream/Views/Manage/Info.tsx
- src/pages/Stream/Views/Manage/Management.tsx
- src/pages/Stream/components/EventTimeLineGraph.tsx
- src/pages/Stream/index.tsx
- When no data is ingested to a new stream, the query calls fails.
- Moved `/info` call to stream load, to use the `first-event-at` from the response
- If the `first-event-at` is not present then don't make query calls.
> Moving the /info API call on stream load

- src/hooks/useQueryLogs.ts
- Updated the `appendOffsetToQuery` function to properly handle both:
- Adding the `OFFSET` clause if it is missing.
- Updating the existing `OFFSET` clause with the provided offset value.
- This ensures the correct offset is applied in all cases.Ï
> fix: Add or update OFFSET clause in query

- src/hooks/useGetStreamMetadata.ts
- src/pages/Home/index.tsx
- Added a null check for `userRoles` in `getStreamMetadata` to prevent premature execution of filtering logic.
- Updated `Home` component to use `useEffect` for conditional invocation of `getStreamMetadata` when `userRoles` is populated.
> fix: handle null userRoles in stream metadata fetching logic

- src/pages/Stream/Views/Explore/LogsViewConfig.tsx
- src/pages/Stream/components/Sidebar.tsx
- src/pages/Stream/index.tsx
- src/pages/Stream/styles/LogsViewConfig.module.css
- src/pages/Stream/styles/SideBar.module.css
Collapsed State:
Expanded State:
Keyboard Shortcut for Collapsing: `Ctrl + /` or `Cmd + /`
> feat: Collapse feature for LogTable sidebar.

- src/pages/Stream/components/Querier/FilterQueryBuilder.tsx
- Updated RuleView component to replace the Input for value with an Autocomplete.
- Added handling for unique column values based on selected field.
> feat: Add Autocomplete for Value Selection in RuleView Component

- src/pages/Stream/Views/Explore/StaticLogTable.tsx
**Issue**
The alternating background colour in table view of explore was missing
**Fix**
This PR fixes the issue with the ability of highlight the selected cell without changing the behaviour of the rest of the table
> Table Cell background color fix

- src/pages/Dashboards/CreateTileForm.tsx
- src/pages/Stream/providers/FilterProvider.tsx
Issue:
navigating to edit tile didn't retain previous tile values
Fix: 
This PR introduces an exit condition to edit option which allows the tile details to retain
Also introduces a new reducer to clear applied filter query
> Fix: Edit Tile Modal Dashboards

- src/pages/Stream/components/Querier/FilterQueryBuilder.tsx
This PR introduces
- Filter Builder Rules limited to 2 rules and per rules condition limited to 2 conditions
- Live query pills on filter builder modal
> Limit Filter builder rules

- package.json
- src/hooks/useHotTier.ts
- src/pages/Stream/Views/Manage/Management.tsx
- src/pages/Stream/Views/Manage/Settings.tsx
This PR adds the following:
- refresh button to fetch the latest hot tier data
- changes in position of delete button 
- change delete button from icon to a text button
> hot tier refresh

- src/hooks/useAlertsEditor.tsx
This PR removes the redundant alerts api call from the manage page
> remove redundant alerts api call
