package-lock.json
package.json
src/App.js
src/components/SideDialog/index.js
src/page/Dashboard/DateTimeRangePicker.js
src/page/Dashboard/index.js
src/page/Login/index.js
src/utils/api/constants.js
src/utils/api/index.js
src/utils/api/logstreams.js
src/utils/api/query.js

Add react-query

---

src/page/Dashboard/index.js

Fix empty log stream

---

package-lock.json
package.json
src/page/Dashboard/DatePicker.css
src/page/Dashboard/DatePicker.js
src/page/Dashboard/DateRangeSeletor.js
src/page/Dashboard/index.js

Add new calendar

---

src/components/SideDialog/index.js
src/page/Dashboard/index.js
src/utils/api/query.js

Also, change the field separator for tags and metadata
to '^' from earlier ','.

Ignore scrolling query till we fix the issues with query

---

src/utils/api/index.js

Made the adding of '/' as per the status of URL.

Made changes in the getServerURL() function

---

src/utils/api/query.js

Sorted log records by time field in reverse order

---

src/@types/parseable/api/query.ts
src/components/Header/HeaderBreadcrumbs.tsx
src/components/Header/Layout.tsx
src/components/Header/RefreshInterval.tsx
src/components/Header/RefreshNow.tsx
src/components/Header/Search.tsx
src/components/Header/SubHeader.tsx
src/components/Header/TimeRange.tsx
src/components/Header/index.tsx
src/components/Navbar/index.tsx
src/layouts/MainLayout/Context.tsx
src/pages/Logs/LogTable.tsx
src/pages/Query/QueryCodeEditor.tsx

Separate routing system for header

Clean header

---

src/components/Navbar/index.tsx

Error: If user enter this in browser  
`http://localhost:3001/backend/config`
Nav router redirect to 
`http://localhost:3001/backend/query`

Route redirection 

---

src/pages/Stats/Alerts.tsx
src/pages/Stats/Status.tsx
src/pages/Users/row.tsx
src/pages/Users/styles.tsx

[user] thead style fix
[users] update role-> add role
[stats] reload alerts on page revisit
[stats] status count bugs fixed

Final touches

---

src/pages/Logs/Column.tsx
src/pages/Logs/LogRow.tsx
src/pages/Logs/LogTable.tsx
src/pages/Logs/styles.tsx

Added feature to pin columns
Seems mostly feature complete, lmk what you think

feat: pinning columns

---

src/api/llm.ts
src/components/Header/PrimaryHeader.tsx
src/components/Navbar/infoModal.tsx
src/hooks/usePostLLM.tsx
src/layouts/MainLayout/Context.tsx
src/pages/Login/index.tsx
src/pages/Query/QueryCodeEditor.tsx
src/pages/Query/index.tsx
src/pages/Stats/styles.tsx

isLLMactive Shift to global Context and Set default limit on query page

---

src/hooks/usePostLLM.tsx
src/pages/Query/QueryCodeEditor.tsx

- minor prettier formatting as well
- update notification text while generating sql

Improve llm comment message after SQL generation

---

src/hooks/useLoginForm.ts
src/utils/index.ts

initial setup and login page autofill

Query Params

---

src/@types/parseable/api/about.ts
src/components/Navbar/infoModal.tsx
src/utils/index.ts

UI Version added and Query params json parse fixed

---

src/components/Header/PrimaryHeader.tsx

<Link> react component changed to <a>

logo url bug

---

src/pages/AccessManagement/Roles.tsx

Label renamed - Set Default OIDC Role

Label renamed - Set Default OIDC Role

---

src/components/Navbar/index.tsx
src/components/Navbar/rolesHandler.ts
src/pages/AccessManagement/Users.tsx

Fixes #157
Description:
This PR addresses the issue identified in bug #157. This fix ensures even when there are no streams present user button will still show up.

fix user button bug

---

src/api/caching.ts
src/api/constants.ts
src/hooks/useGetCacheStatus.tsx
src/hooks/usePutCache.tsx
src/pages/Config/index.tsx
src/pages/Config/styles.tsx

Add Toggle Button for Cache on Config Page
Description: 
This PR introduces a toggle button on the Config page to enable or disable caching.

add cache button in config

---

src/@types/parseable/api/about.ts
src/components/Navbar/infoModal.tsx

Also see https://github.com/parseablehq/parseable/pull/597
Fixes https://github.com/parseablehq/parseable/issues/593

add cache information from About API to the About page

---

src/pages/AccessManagement/Roles.tsx
src/pages/AccessManagement/Users.tsx

#180 
- "Create User Modal " : disabled the create button if password is created
- update the role in create user modal if user add new role
- change the create role modal title

"Update roles in 'Create User if a new role is added"

---

src/components/Header/Querier.tsx
src/components/Header/SubHeader.tsx
src/components/Header/styles/QueryBuilder.module.css
src/pages/Home/index.tsx

Fixes for:
1. Irregular scrollbars for the filter section
2. The header looks collapsed on the homepage
3. Filterbar width adjustments
4. Remove search bar

postcss migration feedbacks

---

src/pages/Logs/LogTable.tsx

fixed the count(*) at the bottom of explore screen

fixed the count(*) at the bottom of explore screen

---

src/pages/Systems/MachineInfo.tsx
src/pages/Systems/styles/Systems.module.css

This PR updates the copy button on cluster page which is more aligned to the theme of the application. On hover the background should be transparent and the color will be blue.

Styling Update

---

src/hooks/useQueryLogs.ts
src/hooks/useQueryResult.tsx

This PR fixes a bug where the footer loader was not synced with the query

Footer loader was not synced with the query

---

src/hooks/useLogStream.tsx
src/pages/Home/CreateStreamModal.tsx

Fixed: Multiple clickable create button which will lead to error notification because it will send same request to the server multiple times
Create button has a loader now

Create stream Button

---

src/components/Navbar/infoModal.tsx
src/components/Navbar/styles/InfoModal.module.css

The Upgrade to latest version in about modal was distorted. This PR aligns the styling of that button

Upgrade Button Styling  Fix

---

src/hooks/useRole.tsx
src/pages/AccessManagement/Roles.tsx

**Issue** 
On changing the default role the data wont mutate
**Fix**
put /role/default 
doesn't respond with a data object, so the get role/default is called again

default oidc role mutate

---

src/pages/Stream/Views/Manage/Settings.tsx

**Feature**
This PR allows User with standalone deployments to enable hot tier

Hot Tier for standalone deployments

---

src/hooks/useGetStreamMetadata.ts
src/layouts/MainLayout/index.tsx
src/pages/Home/index.tsx
src/pages/Home/styles/Home.module.css

Fixes https://github.com/parseablehq/console/issues/347

Home Screen-Loading & error state fixes (#347)

---

src/components/Header/TimeRange.tsx
src/constants/timeConstants.ts
src/hooks/useDashboards.tsx
src/pages/Dashboards/Dashboard.tsx
src/pages/Dashboards/hooks/useParamsController.ts
src/pages/Dashboards/index.tsx
src/pages/Dashboards/providers/DashboardsProvider.ts
src/pages/Stream/providers/LogsProvider.tsx
src/utils/timeRangeUtils.ts

Requirement: Implement url search parameters. 
Implementation: Instead of updating search parameters inside every component's instance, a hook (which acts as middleware) listens to the store and updates the search parameters. This also listens for any URL change and updates the store.

params controller hook

---

src/components/Header/styles/HelpModal.module.css
src/pages/Dashboards/index.tsx
src/pages/Systems/index.tsx

Update:
Proper Page Title was missing from Cluster Page and Dashboards Page.
Buttons in Help Modal was not updated with the current theme of the console

Udpate Title based on page

---

src/hooks/useDashboards.tsx
src/pages/Dashboards/CreateTileForm.tsx

Resolved issue where the query parameter was being passed as empty string to the Query API.

Resolved issue of query API on dashboard page.

---

package.json
src/@types/parseable/api/about.ts
src/@types/parseable/api/clusterInfo.ts
src/@types/parseable/api/stream.ts
src/api/caching.ts
src/api/constants.ts
src/components/Navbar/infoModal.tsx
src/hooks/useCacheToggle.tsx
src/pages/Stream/providers/StreamProvider.tsx
src/pages/Systems/MachineInfo.tsx

This PR removes caching options from console.
Cache Values removed from UI in :
1. Info Modal
2. Cluster Page (Ingestor Info and querier info)

Removed Caching from console
